### ISSUE TITLE
HTML CODE REVIEW -<br> in <p> tags

### ISSUE THREAD

**Issue by Lutrian1** [Clarice-COD/look-and-feel-corporate-identity#3]
Dit is wel erg old school. Hoe je dit kan fixen is of in je css margins maken om ervoor te zorgen dat de tekst in een blok past. Dit zorgt ervoor dat het automatisch afbreekt en daardoor fatsoenlijk leesbaar is.

**Comment by Lutrian1** [comment]
een main is ook dat de screen reader dan constant spaties tussen de woorden leest

**Comment by Clarice-COD** [comment]
Ik heb de `br` tag in de `p` tag vervangen met een max-width in css [CSS](https://github.com/Clarice-COD/look-and-feel-corporate-identity/blob/main/stylesheet.css#L278) [HTML](https://github.com/Clarice-COD/look-and-feel-corporate-identity/blob/main/agenda.html#L45-L47)

**Comment by Clarice-COD** [comment]
Ik heb de br tag in de p tag vervangen met een max-width in css [CSS](https://github.com/Clarice-COD/look-and-feel-corporate-identity/blob/main/stylesheet.css#L278) [HTML](https://github.com/Clarice-COD/look-and-feel-corporate-identity/blob/main/agenda.html#L45-L47)
